name: test
on:
  #push:
  #  branches:
  #    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Buildx
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker buildx build --load -t apptest7 ./container_image_processing
      - name: Run tests
        run: docker run apptest7 pytest /src/
  #test2:
  #  needs: test
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v3
  #    - name: Cache Buildx
  #      uses: actions/cache@v3
  #     with:
  #        path: /tmp/.buildx-cache
  #        key: ${{ runner.os }}-buildx-${{ github.sha }}
  #        restore-keys: |
  #          ${{ runner.os }}-buildx-
  #    - name: Set up buildx
  #      uses: docker/setup-buildx-action@v1
  #   - name: Build Docker image
  #      run: docker buildx build --load -t apptest7 ./container_image_processing
